packages:
  - "components/packages/*/*"
  - "components/presets/*"
  - "components/adapters/*"
  - "components/products/*"
  - "components/tokenpilot/packages/*"
  - "components/tokenpilot/packages/*/*"
  - "components/tokenpilot/presets/*"
  - "components/tokenpilot/adapters/*"
  - "components/tokenpilot/products/*"
  - "apps/*"
