export function formatCliUsage(): string {
  return [
    "Usage:",
    "  lightmem2 <command>",
    "  lightmem2 <host> <command>",
    "  lightmem2 <host> session <session-id> <command>",
    "",
    "Hosts:",
    "  openclaw",
    "  codex",
    "  claude-code",
    "",
    "Top-level commands:",
    "  status",
    "  report",
    "  doctor",
    "  visual",
    "  mode <conservative|normal|aggressive>",
    "  settings details <on|off>",
    "  stabilizer ...",
    "  reduction ...",
    "  eviction ...",
    "  context",
    "  use <host>",
    "  use <host> session <session-id>",
    "",
    "Examples:",
    "  lightmem2 report",
    "  lightmem2 openclaw doctor",
    "  lightmem2 claude-code doctor",
    "  lightmem2 openclaw session 123e4567-e89b-12d3-a456-426614174000 report",
    "  lightmem2 use openclaw",
  ].join("\n");
}
